[env:lilygo-t-dongle-s3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_unflags =
    -DARDUINO_USB_MODE=1

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
    esp32async/AsyncTCP@^3.3.2
    esp32async/ESPAsyncWebServer@^3.6.0

board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
